import { useEffect, useState } from 'react';
import { Download, Receipt, WifiOff } from 'lucide-react';
import CheckoutForm from '../components/CheckoutForm.jsx';
import CartSidebar from '../components/CartSidebar.jsx';
import { useCart } from '../context/CartContext.jsx';
import { api, queueSale, queuedCount } from '../utils/api.js';
import { formatZmw } from '../utils/currency.js';
import { downloadReceipt } from '../utils/receipt.js';

export default function CheckoutPage() {
  const { cart, clearCart } = useCart();
  const cashierName = JSON.parse(localStorage.getItem('pos_user') || '{}').name || 'FreshMart cashier';
  const [customerName, setCustomerName] = useState(''); const [payment, setPayment] = useState('CASH'); const [discount, setDiscount] = useState(0); const [message, setMessage] = useState(''); const [lastSale, setLastSale] = useState(null); const [offline, setOffline] = useState(!navigator.onLine);
  useEffect(() => { const online = () => setOffline(false); const offlineHandler = () => setOffline(true); addEventListener('online', online); addEventListener('offline', offlineHandler); return () => { removeEventListener('online', online); removeEventListener('offline', offlineHandler); }; }, []);
  const sale = async (event) => { event.preventDefault(); if (!cart.length) return; const payload = { customerName, items: cart.map((product) => ({ productId: product.id, quantity: product.quantity })), paymentMethod: payment, discountPercent: discount }; try { const data = offline ? null : await api('/sales', { method: 'POST', body: JSON.stringify(payload) }); if (offline) { queueSale(payload); setMessage('Network unavailable. Sale queued securely for sync.'); } else { setMessage('Purchase confirmed. Receipt ready.'); setLastSale(data.sale); window.dispatchEvent(new Event('inventory-updated')); } clearCart(); } catch (error) { queueSale(payload); setMessage(`Sale queued for retry: ${error.message}`); } };
  return <><div className="header"><div><div className="eyebrow">Till 01 / {offline ? 'offline queue' : 'live'}</div><h1>Checkout</h1><p className="muted">Review the sale and confirm payment.</p></div>{offline && <div className="notice"><WifiOff size={15} style={{ verticalAlign: '-3px' }} /> {queuedCount()} queued</div>}</div>{message && <div className="notice">{message}</div>}<div className="grid checkout"><section className="panel"><h2>Customer and payment</h2><p className="muted">Add the customer details before completing this purchase.</p><CheckoutForm customerName={customerName} setCustomerName={setCustomerName} payment={payment} setPayment={setPayment} onSubmit={sale} disabled={!cart.length} /></section><CartSidebar discount={discount} setDiscount={setDiscount} formId="checkout-form" /></div>{lastSale && <section className="panel receipt"><h2><Receipt size={20} style={{ verticalAlign: '-3px' }} /> Receipt summary</h2><p className="muted">Receipt {lastSale.receiptNumber} · {customerName || 'Walk-in customer'}</p><div className="receipt-items">{lastSale.items.map((item) => <div className="cart-line" key={item.id}><span>{item.name} x{item.quantity}</span><strong>{formatZmw(item.lineTotal)}</strong></div>)}</div><p className="muted">Subtotal: {formatZmw(lastSale.subtotal)} · Discount: {formatZmw(lastSale.discount)}</p><div className="total"><span>Total paid</span><strong>{formatZmw(lastSale.total)}</strong></div><p className="muted">Payment: {lastSale.payment.method} · Transaction ID: {lastSale.id}</p><button className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 active:scale-95 transition transform duration-150 ease-in-out" onClick={() => downloadReceipt(lastSale, { cashierName, customerName })}><Download size={16} style={{ verticalAlign: '-3px' }} /> Download Receipt</button></section>}</>;
}