import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../utils/api.js';

export default function HomePage({ user, onLogin }) {
  const navigate = useNavigate(); const [email, setEmail] = useState('cashier@freshmart.local'); const [password, setPassword] = useState('demo123'); const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); try { const data = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('pos_token', data.token); localStorage.setItem('pos_user', JSON.stringify(data.user)); onLogin(data.user); navigate('/catalog'); } catch (err) { setError(err.message); } };
  if (user) return <section><div className="eyebrow">FreshMart / {user.role === 'MANAGER' ? 'manager workspace' : 'cashier workspace'}</div><h1>Good morning,<br /><em>{user.name.split(' ')[0]}.</em></h1><p className="muted">Browse the catalog, build a sale, and confirm payment at checkout.</p><div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', marginTop: 28 }}><button className="panel" onClick={() => navigate('/catalog')}><h2>Open catalog</h2><p className="muted">Browse products and add items to the current sale.</p></button><button className="panel" onClick={() => navigate('/checkout')}><h2>Go to checkout</h2><p className="muted">Review the cart, collect payment, and issue a receipt.</p></button>{user.role === 'MANAGER' && <button className="panel" onClick={() => navigate('/dashboard')}><h2>Open dashboard</h2><p className="muted">Review sales health and inventory signals.</p></button>}</div></section>;
  return <main className="max-w-lg mx-auto p-6 bg-white rounded-lg shadow-md" style={{ marginTop: '10vh' }}><div className="eyebrow">FreshMart / secure access</div><h1 className="text-xl font-bold mb-4">Good morning.<br /><em>Ready to serve?</em></h1><p className="muted">Sign in to your point of sale workspace.</p><form onSubmit={submit}><div className="field"><label htmlFor="email">Email</label><input id="email" className="search" value={email} onChange={(event) => setEmail(event.target.value)} type="email" /></div><div className="field"><label htmlFor="password">Password</label><input id="password" className="search" value={password} onChange={(event) => setPassword(event.target.value)} type="password" /></div>{error && <p className="error">{error}</p>}<button className="primary" type="submit">Sign in</button></form></main>;
}